### ISSUE TITLE
[Bug Report] missing type defination in vuepress-types

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-community#10]
I turn on `noImplicitAny` in my tsconfig, and that will cause issue when I want to convert ts file in to js.

```
node_modules/vuepress-types/types/plugin.d.ts:42:19 - error TS7006: Parameter 'config' implicitly has an 'any' type.

42   chainWebpack?: (config, isServer: boolean) => void
                     ~~~~~~

node_modules/vuepress-types/types/plugin.d.ts:49:20 - error TS7006: Parameter 'config' implicitly has an 'any' type.

49   chainMarkdown?: (config) => void
```

**Comment by Mister-Hope** [comment]
I think it's fine to jusst mark them as any, because we don't really expect to get type lint here.

**Comment by meteorlxy** [comment]
- VuePress is using old version of `webpack-chain`, so the types of `chainWebpack` is missing yet. I've upgraded `webpack-chain` in vuepress repo, and it will be available in next relaese.

- `markdown-it-chain` has no types definitions now

Yes, `any` is OK here. For now you can disable `noImplicitAny` as a workaround

**Comment by Mister-Hope** [comment]
By the way, when will you release the next version, it's been nearly three month, and I have to make a workaround for a bug which is fixed in master.

**Comment by meteorlxy** [comment]
Most of the team members do not have access to publish npm package of vuepress.

We are waiting for ulivz to release next version, too.

**Comment by Mister-Hope** [comment]
Got it! 😃
