### ISSUE TITLE
[Question] isServer in plugin option api

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-community#12]
I am reading vuepress's source code, and I found pwa plugin is using a `isServer` property [here](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-pwa/lib/enhanceAppFile.js) at line 13.

But the docs and  the `EnhanceApp` type from `vuepress-types` is not metioning it.

When I ran it on my computer, I didnot see this property.

So is this property missing in docs and types, or ULIVZ make a mistake here?

BTW, I am opening issue here because `vuepress-types` give me an error at this file.

**Comment by meteorlxy** [comment]
Yes, it's missed in the docs, only appears in the source code. I'll update it
