### ISSUE TITLE
[Question] Installation command 

### ISSUE THREAD

**Issue by jjangga0214** [vuepress/vuepress-community#14]
## What's your question?

![Screenshot from 2020-01-13 23-25-33](https://user-images.githubusercontent.com/28584151/72263393-2098d700-365c-11ea-8e6d-6777a96a0198.png)

Why does every plugins' installation command example installs packages as `dependencies`, not `devDependencies`? They are only used for build process, which should be `devDependencies`.

**Comment by meteorlxy** [comment]
Well, that depends. If users are building a vuepress-theme or some other packages, plugins should be dependencies.

**Comment by jjangga0214** [comment]
@meteorlxy I see. However I still guess most people(statistically?) who will see it would be Vuepress `user`, who just wants to install them as devDependency. For them, it'd be cumbersome to edit pasted command. So I think we can make it more "user-friendly" docs by fixing those commands. How do you think?

**Comment by meteorlxy** [comment]
It's not a critical point 😄 

Let's "guess" developers understand what it is before copy and paste.

**Comment by meteorlxy** [comment]
After some consideration, I've updated the installation guide. Thanks for you suggestion ❤️
