### ISSUE TITLE
[Question] How can I get parsed markdown from vuepress-plugin-container?

### ISSUE THREAD

**Issue by YunYouJun** [vuepress/vuepress-community#20]
## Environment

- Package version: vuepress-plugin-containerx@2.1.2
- VuePress version: vuepress@1.2.0
- OS: Mac OS Catalina 10.15.3
- Browser: Chrome 79.0.3945.130

## What's your question?

How can I get parsed markdown from [vuepress-plugin-container](https://vuepress.github.io/zh/plugins/container/)?
I cannot find it in [docmention](https://vuepress.github.io/zh/plugins/container/#%E5%AE%89%E8%A3%85).

I want to implement a demo type container.

I just need input:

```md
::: demo
<button class="demo">demo</button>
:::
```

Then I can get:

![image](https://user-images.githubusercontent.com/25154432/73608377-38c99980-45fd-11ea-8305-8715006cdd5f.png)

and display its code:

```html
<button class="demo">demo</button>
```

But I cannot get the code in markdown.

By the way, I think this is a useful function. It can be added as a default feature like `:::tip`.

**Comment by meteorlxy** [comment]
What do you mean by "get parsed markdown"?

Do you want to get the literal code, rather than HTML rendered? So why not wrap it in markdown code block?

```md
::: demo
```html
<button class="demo">demo</button>
```
:::
```

**Comment by meteorlxy** [comment]
Uh I guess I got your point. You want to get both "rendered HTML" and "literal code" in the mean time.

An interesting feature. I have no good idea for now.

Maybe there are two different ways for this:

- Pure markdown-it
- markdown-it + vue

🤔

**Comment by meteorlxy** [comment]
Currently we repeat the code for demo. You can check how vuepress official docs does:

https://github.com/vuejs/vuepress/blame/master/packages/docs/docs/guide/markdown.md#L90-L100

**Comment by YunYouJun** [comment]
Yeah! Thank you for your reply. 
I think it is a good feature for docs.
Maybe this can be a [Feature request]?

**Comment by meteorlxy** [comment]
In fact I think it is out of scope of plugin-container. We can make it another plugin, or intergrate it into vuepress' default theme

**Comment by YunYouJun** [comment]
I find bootstrap and element both use similar features.

Bootstrap use hugo-plugin.
[button.md - bootstrap](https://github.com/twbs/bootstrap/blame/master/site/content/docs/4.3/components/buttons.md#L13)

And element write some configs about markdown-it.
[md-loader - element](https://github.com/ElemeFE/element/tree/dev/build/md-loader)

**Comment by meteorlxy** [comment]
I see. ElementUI is using "markdown-it + vue" way as I mentioned above. See https://github.com/ElemeFE/element/blob/0706805226cc8ad90011a568c1a14bf0701abd37/examples/components/demo-block.vue

**Comment by YunYouJun** [comment]
Yeah, I also used this method to implement the container of demo.
I think this way is more convenient for users to customize styles and layouts.

**Comment by henrikdahl** [comment]
I did the same but I have issues with the script part of demo code. For example if I got two components going through the demo, they seem to apply as a parent and overwrite each other. So the last demo I made is the only `script` that goes through.

Meaning I can't have multiple demo examples on the same page. Not sure why, can't see the difference between method and Elements method.

Anyone else have that issue?

**Comment by henrikdahl** [comment]
This part handles displaying the code to a PrismJS component I created in Vue. Works well. Now to handle the rendering of the demo-component tag.

```
markdown: {
        extendMarkdown: (markdown) => {
            markdown.renderer.rules.fence = (tokens, idx, options, env, self) => {
                const token = tokens[idx]
                const prevToken = tokens[idx - 1]
                const isInDemoComponent = prevToken && prevToken.nesting === 1 && prevToken.info.trim().match(/^demo\s*(.*)$/)
                
                if (token.info === 'html' && isInDemoComponent) {
                    return `<template slot="code">${markdown.utils.escapeHtml(token.content)}</template>`
                }
            }
            
            markdown.use(require('markdown-it-container'), 'demo', {
                    validate: (params) => {
                        return params.trim().match(/^demo\s*(.*)$/)
                    },
                    
                    render: (tokens, idx) => {
                        const { nesting, info } = tokens[idx]
                        const nextToken = tokens[idx + 1]
                        const content = nextToken.type === 'fence' ? nextToken.content : ''
                        
                        if (nesting === 1) {
                            return `
                                <DemoComponent>
                                    <!--demo-component: ${content} :demo-component-->
                            `
                        }
                        
                        return '</DemoComponent>'
                }
            })
        }
    },
```

The previous method I used to render the components failed to handle script tags well. Like I mentioned previously, they kept replacing one an other if there was multiple ones.

Hoping this new approach based on ElementUI will solve it, will comment again if I find a good solution for that part.

**Comment by YunYouJun** [comment]
@henrikdahl Looks good!
BTW, I found two plugins about demo code.
[vuepress-plugin-demo-code](https://github.com/BuptStEve/vuepress-plugin-demo-code)
[vuepress-plugin-demo-block](https://github.com/xiguaxigua/vuepress-plugin-demo-block)

**Comment by henrikdahl** [comment]
@YunYouJun 

This plugin has the same bug I mentioned above: https://github.com/BuptStEve/vuepress-plugin-demo-code

Was using that one as a reference to begin with.

The other one doesn't use a Vue component as a base which is a requirement for me. I'm thinking it might share the same bug as well. Haven't tried that one.

I got it to render both the code and the demo part, however the script tag throws an error and hence the components don't work properly.

Sample image: 
<img width="819" alt="Screenshot 2020-03-05 at 16 03 12" src="https://user-images.githubusercontent.com/1430576/75994208-e7ae0d80-5efa-11ea-823c-4eee1c88013f.png">

DemoComponent:

```
<template>
	<div class="demo-component">
		<div class="demo-component__demo">
			<slot name="demo" />
		</div>
		<div
			ref="code"
			class="demo-component__code"
		>
			<div
				ref="prism"
				class="demo-component__code__prism"
			>
				<PrismComponent>
					<slot name="code" />
				</PrismComponent>
			</div>
		</div>
		<div
			class="demo-component__control"
			@click="onClick"
		>
			<div
				class="demo-component__control__arrow"
				:class="{ 'is-expanded': expanded }"
			/>
		</div>
	</div>
</template>

<script>
export default {
	name: 'DemoComponent',
	
	data() {
		return {
			expanded: false
		}
	},
	
	computed: {
		prismHeight() {
			return this.$refs.prism.clientHeight
		}
	},
	
	methods: {
		onClick() {
			this.expanded = !this.expanded
		}
	},
	
	watch: {
		expanded(value) {
			this.$refs.code.style.height = value ? `${this.prismHeight}px` : '0'
		}
	}
}
</script>

<style scoped lang="scss">
.demo-component {
	margin: 24px 0;

	border: 1px solid #dfe2e5;
	border-radius: 6px;
	
	transition: box-shadow 0.2s;
	
	&:hover {
		box-shadow: 0 0 8px 0 rgba(0, 0, 0, 0.06), 0 2px 4px 0 rgba(0, 0, 0, 0.05);
	}
}

.demo-component__demo {
	display: flex;
	
	position: relative;
	
	padding: 24px;
	
	.toggle-component {
		margin: 20px 20px 20px 0;
	}
}

.demo-component__code {
	height: 0;
	
	overflow: hidden;
	
	transition: height 0.2s;
}

.demo-component__code__prism {
	border-top: 1px solid #dfe2e5;
	
	.prism-component {
		border-radius: 0;
		
		pre {
			margin: 0;
		}
	}
}

.demo-component__control {
	position: relative;
	
	height: 44px;
	
	background-color: #fff;
	border-top: 1px solid #dfe2e5;
	border-radius: 0 0 6px 6px;
	
	cursor: pointer;
	
	&:hover {
		background-color: rgba(27, 31, 35, 0.02);
	}
}

.demo-component__control__arrow {
	content: '';
	
	position: absolute;
	top: 50%;
	left: 50%;
	
	width: 0;
	height: 0;
	
	border-top: 7px solid #ccc;
	border-right: 5px solid transparent;
	border-left: 5px solid transparent;

	transform: translate(-50%, -50%);
	
	transition: border-color 0.3s;
	
	&.is-expanded {
		border-top: none;
		border-right: 5px solid transparent;
		border-bottom: 7px solid #ccc;
		border-left: 5px solid transparent;
	}
	
	.demo-component__control:hover & {
		border-top-color: #3eaf7c;
		border-bottom-color: #3eaf7c;
	}
}
</style>

```

**Comment by YunYouJun** [comment]
In fact, I didn't find this problem until you mentioned it.

I think it may be caused by [script-style-hoisting](https://vuepress.vuejs.org/guide/using-vue.html#script-style-hoisting).

I tried it and no better method found.

---

Since they both need `export default`, I think you can write them in `vuepress/componets`.
Then import them by [import-code-snippets](https://vuepress.vuejs.org/guide/markdown.html#import-code-snippets).

`.vupress/components/test-demo1`
```vue
<template>
  <input :disabled="disabled" />
</template>

<script>
export default {
  data() {
    return {
      disabled: true
    };
  }
};
</script>
```

`.vupress/components/test-demo2`
```vue
<template>
  <input :disabled="disabled" />
</template>

<script>
export default {
  data() {
    return {
      disabled: false
    };
  }
};
</script>
```

Docs markdown
```md
<test-demo1/>

<<< @/docs/.vuepress/components/test-demo1.vue

<test-demo2/>

<<< @/docs/.vuepress/components/test-demo1.vue
```

It works.
![QQ20200306-001712@2x.png](https://i.loli.net/2020/03/06/bucDZz4fahSEQOe.png)
