### ISSUE TITLE
[Question] vuepress-plugin-typescript

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-community#21]
I am meeting some problems, some of my plugins is using `vuepress-plugin-typescript`, and I am using them together. So there are muti instance of `vuepress-plugin-typescript`, and it seems that it will cause a file been handle several time?

![image](https://user-images.githubusercontent.com/33315834/75004687-e9adb080-54a6-11ea-95f1-6543fdb6d936.png)

How I can deal with it ? 

Can vuepress just support typescript by it's own?

**Comment by meteorlxy** [comment]
I remember vuepress will only use a plugin once if it is invloved several times. (without `multiple: true` in plugin)

In your screenshot, I cannot see ts-loader, so why you think it is caused by vuepress-plugin-typescript?

**Comment by Mister-Hope** [comment]
Another question, I am meeing GC issues when vuepress is rendering HTML, I hope you can have I look because I can't reproduce it after removing `vuepress-plugin-typescript`.

[See here](https://github.com/vuejs/vuepress/issues/2221)
