### ISSUE TITLE
[Feature Request] ts-loaderV7 in vuepress-plugin-typescript

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-community#29]
ts-loader V7 makes only 1 break change : Drop support on Node 8

But vuepress is now supporting Node >= 8.6

Can we make ts-loader a peerDependencies or can we drop Node 8 support since Node 8 is already  end of life?

**Comment by meteorlxy** [comment]
Well, I think it's OK to upgrade it. Just Drop Node 8 in both our repo and vuepress
