### ISSUE TITLE
[Question] How to add my own plugin to this community？

### ISSUE THREAD

**Issue by xuekai-china** [vuepress/vuepress-community#31]
## Environment

- Package version: vuepress-plugin-right-anchor
- VuePress version: vuepress@1.4.1
- OS: mac 10.15.4
- Browser: 81.0.4044.113

## What's your question?

Because of my work, I wrote my own plug-in about vuepress. Can I add it to this community? What do I need to do if I can?

**Comment by xuekai-china** [comment]
See: https://github.com/xuekai-china/vuepress-plugin-right-anchor

**Comment by meteorlxy** [comment]
You can add your plugin to a better place - [Awesome VuePress](https://github.com/vuepressjs/awesome-vuepress)

**Comment by meteorlxy** [comment]
If you really want to add your plugin to this repo, you should write your plugin like other plugins in this repo:

- Same structure
- Typescript & `vuepress-types`
- Documentation (en & zh)

BTW, if you want to join our group, send an email to me with some personal info (CV is better).
