### ISSUE TITLE
[Bug Report] `?.` got error in typescript

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-community#33]
https://github.com/Mister-Hope/vuepress-typescript-bug

Only 9 files, just clone it and run the dev script.

**Comment by meteorlxy** [comment]
Nothing happens?

![image](https://user-images.githubusercontent.com/18205362/80280338-09c34f80-8736-11ea-9320-1aa84b9ebb38.png)

**Comment by meteorlxy** [comment]
https://github.com/vuejs/vuepress/issues/2325
