### ISSUE TITLE
[Bug Report] vuepress-plugin-container didn't work

### ISSUE THREAD

**Issue by ChungZH** [vuepress/vuepress-community#37]
## Environment

- Package version: 2.1.3
- VuePress version: 1.4.1
- OS: Windows 10
- Browser: Edge

## Describe the bug

Can't use container plugin. I tried the tip / warning / danger and other blocks, and they all failed

## Screenshots

![image](https://user-images.githubusercontent.com/42088872/80596254-ac424200-8a58-11ea-89b9-56936a276078.png)

My website: https://chungzh.cn/2020/04/25/qt-signal-slot/

The article file on GitHub: https://github.com/ChungZH/ChungZH.github.io/blob/vuepress/blog/_posts/qt-signal-slot.md

## Expected behavior

Custom block work. 

## Additional context

- [config.js](https://github.com/ChungZH/ChungZH.github.io/blob/vuepress/blog/.vuepress/config.js)
- [CSS file](https://github.com/ChungZH/ChungZH.github.io/blob/vuepress/blog/.vuepress/styles/index.styl#L46) (I don't think this is a CSS error, but I still add it)
- [package.json](https://github.com/ChungZH/ChungZH.github.io/blob/vuepress/package.json)

**Comment by meteorlxy** [comment]
Do not use [Object Style](https://vuepress.vuejs.org/plugin/using-a-plugin.html#plugin-options). Use [Babel Style](https://vuepress.vuejs.org/plugin/using-a-plugin.html#plugin-options) instead.

https://github.com/ChungZH/ChungZH.github.io/blob/5b8585900ff54eddcb2f99304676c25b57d4a2c8/blog/.vuepress/config.js#L147-L159

Check these three keys, and you'll understand the reason

**Comment by ChungZH** [comment]
Thank you !

**Comment by arishojaei** [comment]
I still have this issue.
