### ISSUE TITLE
[Bug Report] ERROR TS18002: The 'files' list in config file 'tsconfig.json' is empty

### ISSUE THREAD

**Issue by salazarr-js** [vuepress/vuepress-community#38]
## Environment

- Package version: `"vuepress-plugin-typescript": "^0.2.0"`
- VuePress version: `"vuepress": "^1.4.1"`
- OS: `macOS Catalina 10.15.3`
- Browser: `Version 80.0.3987.163 (Official Build) (64-bit)`

## Describe the bug
After installing the plugin `vuepress-plugin-typescript` as the [docs](https://vuepress.github.io/en/plugins/typescript/#installation) specify, I got `[tsl] ERROR
      TS18002: The 'files' list in config file 'tsconfig.json' is empty.`

## Steps To Reproduce
1. Install
```sh
npm install -D vuepress-plugin-typescript typescript
```
2. Add plugin to `.vuepress/config.js`
```js
module.exports = {
  ...
  plugins: [
    [ 'vuepress-plugin-typescript'],
    ...
  ],
  ...
}
```
3. Edit a component
```html
<template>...</template>
<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  data: () => ({
    msg: 'Hello, TypeScript in Markdown!',
  })
});
</script>
<styles>...</styles>
```
4. Run `dev`
```sh
vuepress dev notes
```
> In my case, `.vuepress` is inside `notes` folder

## Screenshots
![tsl ERROR TS18002](https://user-images.githubusercontent.com/9486209/80933449-2dbc0c00-8d9a-11ea-9ca3-ad515e1d629a.png)

## Expected behavior
We can expect following the steps in the docs everything works fine out of the box.

## Additional context
If I add an empty `enhanceApp.ts` in `.vuepress` folder everything works fine, but I don't use it.

**Comment by meteorlxy** [comment]
What's the content of your `tsconfig.json`?

Could you please provide a reproduce repo?

**Comment by salazarr-js** [comment]
@meteorlxy in this [repo] (https://github.com/salazarr-js/vuepress-ts) I specify every step I did to get the error message, maybe is not a bug, I don't know if this behavior is by design, but just following the docs I got the error. The `tsconfig.json` and any `.ts` files are required to the plugin to function properly

**Comment by meteorlxy** [comment]
Uh, didn't try a minimal repo with this plugin, so didn't notice this behavior.

I could not figure the root cause immediately.

I guess:

- `ts-loader` requires `typescript` compiler
- `typescript` compiler will use a "parser" to parse the `tsconfig.json`
- If nothing match the `files` or `include` in `tsconfig.json`, the "parser" will throw an error like this

Notice that, the `files` or `include` here has no effects, but it is part of the check.

For example, you can set `files` to anything exists:

```json
{
  "files": ["screenshot.png"]
}
```

Although this file has nothing to do with typescript, it will pass the check of the "parser".

**Comment by salazarr-js** [comment]
nice, what I can do? add a little clarification to the documentation?

**Comment by meteorlxy** [comment]
@salazarr-js It would be nice if you can help 😄

**Comment by Mister-Hope** [comment]
> Uh, didn't try a minimal repo with this plugin, so didn't notice this behavior.
> 
> I could not figure the root cause immediately.
> 
> I guess:
> 
> * ts-loader requires typescript compiler
> * typescript compiler will use a "parser" to parse the `tsconfig.json`
> * If nothing match the `files` or `include` in `tsconfig.json`, the "parser" will throw an error like this
> 
> Notice that, the `files` or `include` here has no effects. It might be ONLY part of the check.
> 
> For example, you can set `files` to anything exists:
> 
> ```json
> {
>   "files": ["screenshot.png"]
> }
> ```
> 
> Although this file has nothing to do with typescript, it will pass the check of the "parser", and everything works well.
> 
> BTW, seems that the `include` property does not respect non-ts files, e.g. `**/*.md` 🤔

That 's correct, we must have something in `files` or `include`
