### ISSUE TITLE
Please ReAdd Your Plugin URLs

### ISSUE THREAD

**Issue by DMiradakis** [vuepress/vuepress-community#65]
VuePress Community,

I noticed that all of the URLs for the plugins maintained by you on the [awesome-vuepress](https://github.com/vuepress/awesome-vuepress#plugins) repository are all broken. Several of the plugins mentioned on this page - whose documentation has been maintained by you - are plugins that I like to regularly refer to, and now, for some reason, they have been removed from your site. For example, one plugin I regularly looked at was [vuepress-plugin-container](https://vuepress.github.io/plugins/container/). The directory that they were living in was `https://vuepress.github.io/plugins/`.

Can you _please_ add the documentation for these plugins back? They are very useful and it is unfortunate that the community can no longer see them. **We need as much VuePress documentation as possible!**

Thanks!

**Comment by meteorlxy** [comment]
It's back https://vuepress-community.netlify.app/

**Comment by DMiradakis** [comment]
Thank you!
