### ISSUE TITLE
[Bug Report] Unable to use the computed var in ts

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-community#7]
## Describe the bug

```ts
  computed: {
    copyright() {
      const author = this.$themeConfig.author || this.$siteTitle;
      const content = {
        'zh-CN': `${this.html}\n-----\n著作权归${author}所有。\n链接：${location}`,
        'en-US': `${this.html}\n-----\nCopyright by ${author}.\nLink: ${location}`
      };

      return content[this.$lang];
    }
  },
```

This will cause issue on the linter since the default `vue` object doesn't have a $themeConfig or $siteTitle property.

**Comment by Mister-Hope** [comment]
I have a look carefully and found `vuepress-type` seems be the work around , but it is not dependent by `vuepress-plugin-typescript`, so did you miss it in the package.json?

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/71652148-440b7a00-2d5e-11ea-850b-ba34eb40647e.png)

**Comment by meteorlxy** [comment]
`vuepress-types` is a experimental package and not necessary, so I didn't add it to the dependencies of `vuepress-plugin-typescript`.

I'll update the documentation for this.

**Comment by Mister-Hope** [comment]
But after I add vuepress-types, I am still catching problems like the sreenshot above.

**Comment by meteorlxy** [comment]
> But after I add `vuepress-types`, I am still catching problems like the sreenshot above.

You need to import it manually

**Comment by Mister-Hope** [comment]
Thanks, but how to import it? Do you mean like this? Or maybe in the tsconfig.json?

```ts
<script lang="ts">
import 'vuepress-types';
import Vue from 'vue';

export default Vue.extend({
  props: {
    html: { type: String, default: '' }
  },

  data: () => ({ location: '' }),

  computed: {
    copyright() {
      const author = this.$themeConfig.author || this.$siteTitle;
      const content = {
        'zh-CN': `${this.html}\n-----\n著作权归${author}所有。\n链接：${location}`,
        'en-US': `${this.html}\n-----\nCopyright by ${author}.\nLink: ${location}`
      };

      return content[this.$lang];
    }
  },

  created() {
    this.location = window.location;
  }
});
</script>
```

**Comment by meteorlxy** [comment]
Have you installed `vuepress-types`?

BTW, it's better to use `vue-class-component` and `vue-property-decorator` for better types checking

**Comment by meteorlxy** [comment]
Documentation updated:

- https://vuepress.github.io/en/plugins/typescript/#types-definitions

**Comment by Mister-Hope** [comment]
I still have a problems, I have `vuepress-types` installed in the root folder (since I am using monorepo), then I got this

```
Uncaught Error: Cannot find module 'vuepress-types'
    at webpackMissingModule (webpack-internal:///../node_modules/ts-loader/index.js?!../node_modules/@vuepress/core/node_modules/cache-loader/dist/cjs.js?!../node_modules/vue-loader/lib/index.js?!../packages/components/src/BreadCrumb.vue?vue&type=script&lang=ts&:9)
    at eval (webpack-internal:///../node_modules/ts-loader/index.js?!../node_modules/@vuepress/core/node_modules/cache-loader/dist/cjs.js?!../node_modules/vue-loader/lib/index.js?!../packages/components/src/BreadCrumb.vue?vue&type=script&lang=ts&:9)
    at Object.../node_modules/ts-loader/index.js?!../node_modules/@vuepress/core/node_modules/cache-loader/dist/cjs.js?!../node_modules/vue-loader/lib/index.js?!../packages/components/src/BreadCrumb.vue?vue&type=script&lang=ts& (app.js:2046)
    at __webpack_require__ (app.js:770)
    at fn (app.js:130)
    at eval (webpack-internal:///../packages/components/src/BreadCrumb.vue?vue&type=script&lang=ts&:2)
    at Module.../packages/components/src/BreadCrumb.vue?vue&type=script&lang=ts& (app.js:2761)
    at __webpack_require__ (app.js:770)
    at fn (app.js:130)
    at eval (webpack-internal:///../packages/components/src/BreadCrumb.vue:3)
```

While vscode can found it.

![image](https://user-images.githubusercontent.com/33315834/71702879-d1a5a300-2e0c-11ea-9979-bef99fa35019.png)

![image](https://user-images.githubusercontent.com/33315834/71702893-e124ec00-2e0c-11ea-942f-66ad81e9ab81.png)

**Comment by Mister-Hope** [comment]
Also, I am catching problems about `vuepress-types`.
Here is the errors, when I include it in my tsconfig.json
![image](https://user-images.githubusercontent.com/33315834/71805513-67f1f700-30a1-11ea-9592-91c7c75214cf.png)

And here is the error I use `import "vuepress-types"`

![image](https://user-images.githubusercontent.com/33315834/71805583-9079f100-30a1-11ea-9919-db8b5db22261.png)

The fist one only causes error on the console panel, but the website works well while the second one is not working.
I am sure vuepress-types is required as dependencies. I am not familiar how node and ts-loader handles a packages only have `types` options declared.

I wounder if you can help me, thanks.

**Comment by meteorlxy** [comment]
You can check the [test cases](https://github.com/vuepress/vuepress-community/tree/master/packages/vuepress-plugin-typescript/test/e2e/docs).

If you still meet some problems, try to open a new issue and provide a reproduce repo
