### ISSUE TITLE
"npm i -D vuepress-type" — code E404

### ISSUE THREAD

**Issue by azertypow** [vuepress/vuepress-community#8]
## Environment

- Package version: vuepress-types@0.6.0
- VuePress version: vuepress@1.2.0
- OS: macos 10.14.6
- Browser: –

## Describe the bug

zh ```npm i -D vuepress-type``` command error

```
code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/vuepress-type - Not found
```

## Screenshots

![image](https://user-images.githubusercontent.com/12177073/71685536-e1839f80-2d98-11ea-9fdb-c8fcf1c65e33.png)

**Comment by meteorlxy** [comment]
typo.. vuepress-types
