### ISSUE TITLE
[Bug Report] Decode hash

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-community#85]
http://121.37.185.5/docs/zh-cn/intro/preface/#%E5%BC%80%E6%BA%90bi%E7%BB%84%E4%BB%B6

![image](https://user-images.githubusercontent.com/33315834/123949649-6030bb80-d9d5-11eb-9839-f70f465a74f8.png)

https://github.com/vuepress/vuepress-community/blob/7feb5c514090b6901cd7d9998f4dd858e0055b7a/packages/vuepress-plugin-smooth-scroll/src/enhanceApp.ts#L37

decodeURI is required here because browsers like newer version Chrome will automaticlly encode hash when copying links.

If this repo still accept PR, I will open one, if not I may fork one.

Waiting for your reply. @meteorlxy

**Comment by meteorlxy** [comment]
You can still open a PR to fix that.
